### ISSUE TITLE
rake -T does not work

### ISSUE THREAD

**Issue by justin808** [sds/slim-lint#10]
```
rake -T                                                                                                                                                1 ↵ ✹ ✭ [12:06:31]
rake aborted!
NameError: uninitialized constant SlimLint::APP_NAME
/Users/justin/.rvm/gems/ruby-2.2.1@madrone/gems/slim_lint-0.5.0/lib/slim_lint/rake_task.rb:115:in `default_description'
/Users/justin/.rvm/gems/ruby-2.2.1@madrone/gems/slim_lint-0.5.0/lib/slim_lint/rake_task.rb:70:in `define'
/Users/justin/.rvm/gems/ruby-2.2.1@madrone/gems/slim_lint-0.5.0/lib/slim_lint/rake_task.rb:63:in `initialize'
/Users/justin/clients/madrone/investor-dashboard/lib/tasks/linters.rake:21:in `new'
/Users/justin/clients/madrone/investor-dashboard/lib/tasks/linters.rake:21:in `<top (required)>'
/Users/justin/.rvm/gems/ruby-2.2.1@madrone/gems/railties-4.2.0/lib/rails/engine.rb:658:in `block in run_tasks_blocks'
/Users/justin/.rvm/gems/ruby-2.2.1@madrone/gems/railties-4.2.0/lib/rails/engine.rb:658:in `each'
/Users/justin/.rvm/gems/ruby-2.2.1@madrone/gems/railties-4.2.0/lib/rails/engine.rb:658:in `run_tasks_blocks'
/Users/justin/.rvm/gems/ruby-2.2.1@madrone/gems/railties-4.2.0/lib/rails/application.rb:438:in `run_tasks_blocks'
/Users/justin/.rvm/gems/ruby-2.2.1@madrone/gems/railties-4.2.0/lib/rails/engine.rb:453:in `load_tasks'
/Users/justin/.rvm/gems/ruby-2.2.1@madrone/gems/railties-4.2.0/lib/rails/railtie.rb:194:in `public_send'
/Users/justin/.rvm/gems/ruby-2.2.1@madrone/gems/railties-4.2.0/lib/rails/railtie.rb:194:in `method_missing'
/Users/justin/clients/madrone/investor-dashboard/Rakefile:7:in `<top (required)>'
(See full trace by running task with --trace)
```

![emacs-x86_64-10_9_justinmbp_local_______users_justin__rvm_gems_ruby-2_2_1_madrone_gems_slim_lint-0_5_0_lib_slim_lint_rake_task_rb____12_18pm_4_01](https://cloud.githubusercontent.com/assets/1118459/7995662/df64ed88-0ab3-11e5-9f02-cc374b04abaf.jpg)

But I see the constant defined. Seems like some order that the modules are loaded or not loaded is causing this issue.

Any ideas? @sds?

**Comment by sds** [comment]
Thanks for the report, @justin808.

Fixed in ed48994811f6561eff680bed0a402c48264bd8ed.
