### ISSUE TITLE
undefined local variable or method `file' for #<SlimLint::Runner:0x00005635b1640108>

### ISSUE THREAD

**Issue by zyk** [sds/slim-lint#127]
```
undefined local variable or method `file' for #<SlimLint::Runner:0x00005635b1640108>
Did you mean?  fail
/home/zyk/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/slim_lint-0.21.0/lib/slim_lint/runner.rb:60:in `rescue in collect_lints'
/home/zyk/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/slim_lint-0.21.0/lib/slim_lint/runner.rb:57:in `collect_lints'
/home/zyk/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/slim_lint-0.21.0/lib/slim_lint/runner.rb:23:in `block in run'
/home/zyk/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/slim_lint-0.21.0/lib/slim_lint/runner.rb:22:in `map'
/home/zyk/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/slim_lint-0.21.0/lib/slim_lint/runner.rb:22:in `run'
/home/zyk/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/slim_lint-0.21.0/lib/slim_lint/cli.rb:91:in `scan_for_lints'
/home/zyk/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/slim_lint-0.21.0/lib/slim_lint/cli.rb:60:in `act_on_options'
/home/zyk/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/slim_lint-0.21.0/lib/slim_lint/cli.rb:32:in `run'
/home/zyk/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/slim_lint-0.21.0/bin/slim-lint:7:in `<top (required)>'
/home/zyk/.rbenv/versions/2.6.7/bin/slim-lint:23:in `load'
/home/zyk/.rbenv/versions/2.6.7/bin/slim-lint:23:in `<top (required)>'
/home/zyk/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:63:in `load'
/home/zyk/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:63:in `kernel_load'
/home/zyk/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:28:in `run'
/home/zyk/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/bundler-2.2.16/lib/bundler/cli.rb:494:in `exec'
/home/zyk/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/zyk/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/home/zyk/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/home/zyk/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/bundler-2.2.16/lib/bundler/cli.rb:30:in `dispatch'
/home/zyk/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/home/zyk/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/bundler-2.2.16/lib/bundler/cli.rb:24:in `start'
/home/zyk/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/bundler-2.2.16/exe/bundle:49:in `block in <top (required)>'
/home/zyk/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/bundler-2.2.16/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
/home/zyk/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/bundler-2.2.16/exe/bundle:37:in `<top (required)>'
/home/zyk/.rbenv/versions/2.6.7/bin/bundle:23:in `load'
/home/zyk/.rbenv/versions/2.6.7/bin/bundle:23:in `<main>'
```

Changing line 60 in in `runner.rb` from
```
        return [SlimLint::Lint.new(nil, file, e.lineno, e.error, :error)]
```
to
```
        return [SlimLint::Lint.new(nil, file_name, e.lineno, e.error, :error)]
```

Gives a better result:
```
app/[REDACTED]/_form.html.slim:61 [E] Expected attribute
```

- Slim-Lint version: 0.21.0
- RuboCop version: 1.14.0
- Ruby version: 2.6.7

**Comment by sds** [comment]
Thanks for the report. Fixed in 5ef60a7d84ca46afd5689cf3ebd9042ad9fd1236 and released in [0.21.1](https://rubygems.org/gems/slim_lint/versions/0.21.1).
